version: '3'

tasks:
  generate-proto:
    cmds:
      - buf generate api/v1/api.proto
  generate-sqlc:
    cmds:
      - sqlc generate
  generate:
    cmds:
      - task: generate-proto
      - task: generate-sqlc

  migrations-apply:
    cmd: atlas schema apply -u "mysql://root:123@localhost:3306/releases" --to file://schema.sql --dev-url "docker://mysql/8/example"

  start-frontend:
    cmds:
      - cd frontend && pnpm start

  start-api:
    cmds:
      - go run main.go

  dev:
    deps:
      - task: start-api
      - task: start-frontend
