// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"database/sql"
	"time"
)

type Release struct {
	GithubID         string
	ID               int32
	RepositoryID     int32
	Name             string
	Url              string
	TagName          string
	Description      string
	DescriptionShort string
	Author           sql.NullString
	IsPrerelease     bool
	ReleasedAt       time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Hash             uint64
}

type Repository struct {
	ID           int32
	GithubID     string
	Name         string
	Url          string
	Private      bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	LastSyncedAt time.Time
	ImageUrl     string
	ImageSize    int32
	Hash         uint64
}

type RepositoryStar struct {
	RepositoryID int32
	UserID       int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Type         int8
}

type User struct {
	ID           int32
	Username     string
	GithubID     uint64
	GithubToken  GitHubToken
	LastSyncedAt time.Time
	PublicID     string
	IsOnboarded  bool
	IsPublic     bool
}
