// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
	"time"
)

type Release struct {
	ID           int32
	RepositoryID int32
	Name         string
	Url          string
	TagName      string
	Description  string
	Author       sql.NullString
	IsPrerelease bool
	ReleasedAt   time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Repository struct {
	ID           int32
	Name         string
	Url          string
	Private      bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	LastSyncedAt time.Time
	ImageUrl     string
	ImageSize    int32
	Hash         int64
}

type RepositoryStar struct {
	RepositoryID int32
	UserID       int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type User struct {
	ID           int32
	Username     string
	GithubToken  GitHubToken
	LastSyncedAt time.Time
}
